-- DCP database schema v0.1
-- Spec: specs/erd-v0.1.md
--
-- Two schemas:
--   platform_*  global: organisations, user accounts, tenant registry
--   tenant_*    per-tenant: everything else. One schema per organisation.
--
-- Isolation is at the schema level, so tenant tables carry no org_id column
-- and no query can accidentally cross tenants by omitting a WHERE clause.
--
-- Primary keys are ULIDs generated by the CLIENT, not the database. Devices
-- create submissions, operations and media while offline and must be able to
-- name them before the server has ever seen them. A server-generated bigserial
-- would make offline creation impossible.

CREATE EXTENSION IF NOT EXISTS postgis;

-- ===========================================================================
-- PLATFORM (global)
-- ===========================================================================

CREATE TABLE platform_organization (
    id              text PRIMARY KEY,
    name            text NOT NULL,
    slug            text NOT NULL UNIQUE,
    schema_name     text NOT NULL UNIQUE,
    created_at      timestamptz NOT NULL DEFAULT now(),
    suspended_at    timestamptz
);

CREATE TABLE platform_user (
    id              text PRIMARY KEY,
    email           text NOT NULL UNIQUE,
    password_hash   text,
    mfa_secret      text,
    status          text NOT NULL DEFAULT 'active',
    last_login_at   timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT platform_user_status_check
        CHECK (status IN ('active', 'invited', 'suspended', 'deactivated'))
);

CREATE TABLE platform_org_membership (
    organization_id text NOT NULL REFERENCES platform_organization (id) ON DELETE CASCADE,
    user_id         text NOT NULL REFERENCES platform_user (id) ON DELETE CASCADE,
    org_role        text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (organization_id, user_id),
    CONSTRAINT platform_org_membership_role_check
        CHECK (org_role IN ('owner', 'admin', 'member'))
);

-- ===========================================================================
-- PROJECTS, ENVIRONMENTS, ACCESS
-- ===========================================================================

CREATE TABLE project (
    id              text PRIMARY KEY,
    name            text NOT NULL,
    slug            text NOT NULL UNIQUE,
    -- Fixed at creation. Changing it would require re-encrypting or decrypting
    -- historical data, which defeats the point of having chosen it.
    security_mode   text NOT NULL DEFAULT 'standard',
    created_at      timestamptz NOT NULL DEFAULT now(),
    archived_at     timestamptz,
    CONSTRAINT project_security_mode_check
        CHECK (security_mode IN ('standard', 'field_level', 'project_e2e'))
);

CREATE TABLE environment (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    kind            text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, kind),
    CONSTRAINT environment_kind_check
        CHECK (kind IN ('development', 'staging', 'production'))
);

CREATE TABLE team (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    name            text NOT NULL,
    parent_team_id  text REFERENCES team (id) ON DELETE SET NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE project_member (
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    user_id         text NOT NULL,
    project_role    text NOT NULL,
    team_id         text REFERENCES team (id) ON DELETE SET NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, user_id),
    CONSTRAINT project_member_role_check
        CHECK (project_role IN ('manager', 'supervisor', 'enumerator', 'analyst', 'viewer'))
);

CREATE TABLE device (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    user_id         text NOT NULL,
    platform        text NOT NULL,
    os_version      text,
    app_version     text,
    -- Highest logical counter the server has accepted from this device.
    -- Ordering depends on it, so it is authoritative state, not a statistic.
    last_counter    bigint NOT NULL DEFAULT 0,
    last_sync_at    timestamptz,
    registered_at   timestamptz NOT NULL DEFAULT now(),
    revoked_at      timestamptz,
    CONSTRAINT device_platform_check
        CHECK (platform IN ('android', 'ios', 'desktop', 'web'))
);

-- ===========================================================================
-- ENCRYPTION KEYS  (specs/encryption-envelope-v0.1.md)
-- ===========================================================================

CREATE TABLE project_key (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    public_key      bytea NOT NULL,
    key_role        text NOT NULL,
    label           text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    revoked_at      timestamptz,
    CONSTRAINT project_key_role_check
        CHECK (key_role IN ('primary', 'backup', 'recovery')),
    CONSTRAINT project_key_length_check
        CHECK (octet_length(public_key) = 32)
);

-- ===========================================================================
-- FORMS
-- ===========================================================================

CREATE TABLE form (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    form_key        text NOT NULL,
    title           text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    archived_at     timestamptz,
    UNIQUE (project_id, form_key)
);

-- Immutable once published. Editing produces a new row, never an UPDATE.
CREATE TABLE form_version (
    id              text PRIMARY KEY,
    form_id         text NOT NULL REFERENCES form (id) ON DELETE CASCADE,
    version         integer NOT NULL,
    ir              jsonb NOT NULL,
    ir_checksum     text NOT NULL,
    published_at    timestamptz,
    published_by    text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (form_id, version)
);

CREATE TABLE form_deployment (
    id              text PRIMARY KEY,
    environment_id  text NOT NULL REFERENCES environment (id) ON DELETE CASCADE,
    form_version_id text NOT NULL REFERENCES form_version (id) ON DELETE RESTRICT,
    deployed_at     timestamptz NOT NULL DEFAULT now(),
    deployed_by     text,
    retired_at      timestamptz
);

-- ===========================================================================
-- ENTITIES AND DATASETS
-- ===========================================================================

CREATE TABLE entity_type (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    type_key        text NOT NULL,
    name            text NOT NULL,
    schema_def      jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, type_key)
);

CREATE TABLE entity (
    id              text PRIMARY KEY,
    entity_type_id  text NOT NULL REFERENCES entity_type (id) ON DELETE CASCADE,
    attributes      jsonb NOT NULL DEFAULT '{}'::jsonb,
    location        geography(Point, 4326),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);

CREATE TABLE entity_relationship (
    id              text PRIMARY KEY,
    from_entity_id  text NOT NULL REFERENCES entity (id) ON DELETE CASCADE,
    to_entity_id    text NOT NULL REFERENCES entity (id) ON DELETE CASCADE,
    relation_kind   text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (from_entity_id, to_entity_id, relation_kind)
);

CREATE TABLE dataset (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    dataset_key     text NOT NULL,
    name            text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, dataset_key)
);

CREATE TABLE dataset_version (
    id              text PRIMARY KEY,
    dataset_id      text NOT NULL REFERENCES dataset (id) ON DELETE CASCADE,
    version         integer NOT NULL,
    row_count       integer NOT NULL DEFAULT 0,
    checksum        text NOT NULL,
    published_at    timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (dataset_id, version)
);

CREATE TABLE dataset_record (
    id                  text PRIMARY KEY,
    dataset_version_id  text NOT NULL REFERENCES dataset_version (id) ON DELETE CASCADE,
    record_key          text NOT NULL,
    data                jsonb NOT NULL,
    UNIQUE (dataset_version_id, record_key)
);

-- ===========================================================================
-- CASES, VISITS, ASSIGNMENTS
-- ===========================================================================

CREATE TABLE case_record (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    entity_id       text REFERENCES entity (id) ON DELETE SET NULL,
    case_key        text,
    status          text NOT NULL DEFAULT 'open',
    priority        integer NOT NULL DEFAULT 0,
    location        geography(Point, 4326),
    due_at          timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    closed_at       timestamptz,
    UNIQUE (project_id, case_key)
);

CREATE TABLE assignment (
    id              text PRIMARY KEY,
    case_id         text NOT NULL REFERENCES case_record (id) ON DELETE CASCADE,
    user_id         text,
    team_id         text REFERENCES team (id) ON DELETE SET NULL,
    assigned_by     text,
    assigned_at     timestamptz NOT NULL DEFAULT now(),
    released_at     timestamptz,
    CONSTRAINT assignment_target_check
        CHECK (user_id IS NOT NULL OR team_id IS NOT NULL)
);

-- A visit is one collection event against a case. Separating it from the case
-- is what makes longitudinal studies and repeat inspections work without
-- overloading a single row.
CREATE TABLE visit (
    id              text PRIMARY KEY,
    case_id         text NOT NULL REFERENCES case_record (id) ON DELETE CASCADE,
    sequence        integer NOT NULL,
    form_version_id text REFERENCES form_version (id) ON DELETE RESTRICT,
    scheduled_at    timestamptz,
    completed_at    timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (case_id, sequence)
);

-- ===========================================================================
-- SUBMISSIONS  (specs/sync-protocol-v0.1.md)
-- ===========================================================================

CREATE TABLE submission (
    id                  text PRIMARY KEY,
    project_id          text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    environment_id      text NOT NULL REFERENCES environment (id) ON DELETE RESTRICT,
    form_version_id     text NOT NULL REFERENCES form_version (id) ON DELETE RESTRICT,
    case_id             text REFERENCES case_record (id) ON DELETE SET NULL,
    visit_id            text REFERENCES visit (id) ON DELETE SET NULL,
    origin_device_id    text REFERENCES device (id) ON DELETE SET NULL,
    created_by          text,
    status              text NOT NULL DEFAULT 'draft',
    started_at          timestamptz,
    finalized_at        timestamptz,
    received_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT submission_status_check
        CHECK (status IN ('draft', 'finalized', 'in_review', 'approved',
                          'rejected', 'correction_required'))
);

-- Append-only. No UPDATE, no DELETE, ever. This table IS the audit trail;
-- rewriting it destroys the correction history the review workflow depends on.
CREATE TABLE submission_content_key (
    id              text PRIMARY KEY,
    submission_id   text NOT NULL REFERENCES submission (id) ON DELETE CASCADE,
    device_id       text NOT NULL REFERENCES device (id) ON DELETE RESTRICT,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (submission_id, device_id)
);

CREATE TABLE submission_wrapped_key (
    content_key_id      text NOT NULL REFERENCES submission_content_key (id) ON DELETE CASCADE,
    project_key_id      text NOT NULL REFERENCES project_key (id) ON DELETE RESTRICT,
    submission_id       text NOT NULL REFERENCES submission (id) ON DELETE CASCADE,
    ephemeral_public    bytea NOT NULL,
    nonce               bytea NOT NULL,
    wrapped_key         bytea NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (content_key_id, project_key_id),
    CONSTRAINT submission_wrapped_key_sizes_check
        CHECK (octet_length(ephemeral_public) = 32
               AND octet_length(nonce) = 12
               AND octet_length(wrapped_key) = 48)
);

CREATE TABLE submission_op (
    id                  text PRIMARY KEY,
    submission_id       text NOT NULL REFERENCES submission (id) ON DELETE CASCADE,
    op_kind             text NOT NULL,
    path                text,
    -- Exactly one of value / value_ciphertext is populated. A project in
    -- field_level mode uses both across different ops in the same submission.
    value               jsonb,
    value_ciphertext    bytea,
    content_key_id      text REFERENCES submission_content_key (id) ON DELETE RESTRICT,
    nonce               bytea,
    device_id           text NOT NULL REFERENCES device (id) ON DELETE RESTRICT,
    actor_id            text,
    counter             bigint NOT NULL,
    wall_clock          timestamptz NOT NULL,
    received_at         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT submission_op_kind_check
        CHECK (op_kind IN ('set', 'unset', 'repeat_add', 'repeat_delete',
                           'finalize', 'reopen')),
    -- Encrypted ops carry key and nonce; plaintext ops carry neither.
    CONSTRAINT submission_op_encryption_check
        CHECK (
            (value_ciphertext IS NULL AND content_key_id IS NULL AND nonce IS NULL)
            OR
            (value_ciphertext IS NOT NULL AND content_key_id IS NOT NULL
             AND nonce IS NOT NULL AND value IS NULL)
        ),
    -- Database-level enforcement of nonce uniqueness. AES-GCM fails
    -- catastrophically on nonce reuse; this costs one index and removes the
    -- entire failure class even if a client has a broken counter.
    UNIQUE (content_key_id, nonce),
    -- Ordering is by (counter, device_id), never wall clock. A device may not
    -- reuse a counter.
    UNIQUE (device_id, counter)
);

CREATE INDEX submission_op_replay_idx
    ON submission_op (submission_id, counter, device_id);

CREATE INDEX submission_op_received_idx
    ON submission_op (received_at);

-- Materialised current state, folded from the op log. Derived data: it can
-- always be rebuilt from submission_op, so it is safe to drop and recompute.
CREATE TABLE submission_state (
    submission_id   text PRIMARY KEY REFERENCES submission (id) ON DELETE CASCADE,
    data            jsonb NOT NULL DEFAULT '{}'::jsonb,
    op_high_water   bigint NOT NULL DEFAULT 0,
    computed_at     timestamptz NOT NULL DEFAULT now()
);

-- Bounds op-log replay. A fresh device pulls the latest snapshot plus the ops
-- after it, rather than the entire history.
CREATE TABLE submission_snapshot (
    id              text PRIMARY KEY,
    submission_id   text NOT NULL REFERENCES submission (id) ON DELETE CASCADE,
    op_count        integer NOT NULL,
    data            jsonb,
    data_ciphertext bytea,
    content_key_id  text REFERENCES submission_content_key (id) ON DELETE RESTRICT,
    nonce           bytea,
    taken_at        timestamptz NOT NULL DEFAULT now()
);

-- Deletion is an operation, not an absence. Tombstones are carried in pull
-- responses so every replica converges.
CREATE TABLE tombstone (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    subject_type    text NOT NULL,
    subject_id      text NOT NULL,
    submission_id   text REFERENCES submission (id) ON DELETE CASCADE,
    path            text,
    device_id       text REFERENCES device (id) ON DELETE SET NULL,
    counter         bigint,
    created_at      timestamptz NOT NULL DEFAULT now(),
    expires_at      timestamptz,
    CONSTRAINT tombstone_subject_check
        CHECK (subject_type IN ('submission', 'repeat_instance', 'case',
                                'entity', 'media'))
);

CREATE INDEX tombstone_pull_idx ON tombstone (project_id, created_at);

-- ===========================================================================
-- MEDIA
-- ===========================================================================

CREATE TABLE media (
    id                  text PRIMARY KEY,
    submission_id       text NOT NULL REFERENCES submission (id) ON DELETE CASCADE,
    -- Deliberately NOT a foreign key to submission_op: an op referencing media
    -- is accepted before the file arrives, so the op may not exist yet.
    op_id               text,
    mime_type           text NOT NULL,
    size_bytes          bigint NOT NULL DEFAULT 0,
    chunk_count         integer NOT NULL DEFAULT 0,
    -- Hash of CIPHERTEXT, never plaintext: hashing plaintext would let the
    -- server confirm two submissions contain the same photograph.
    ciphertext_hash     text,
    encrypted           boolean NOT NULL DEFAULT false,
    content_key_id      text REFERENCES submission_content_key (id) ON DELETE RESTRICT,
    storage_key         text,
    status              text NOT NULL DEFAULT 'pending',
    uploaded_at         timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT media_status_check
        CHECK (status IN ('pending', 'uploading', 'complete', 'failed'))
);

CREATE TABLE media_upload_session (
    id                  text PRIMARY KEY,
    media_id            text NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    chunk_size          integer NOT NULL,
    received_chunks     integer NOT NULL DEFAULT 0,
    expires_at          timestamptz NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now()
);

-- ===========================================================================
-- QUALITY AND REVIEW
-- ===========================================================================

CREATE TABLE quality_rule (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    form_id         text REFERENCES form (id) ON DELETE CASCADE,
    name            text NOT NULL,
    definition      jsonb NOT NULL,
    severity        text NOT NULL DEFAULT 'warning',
    enabled         boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT quality_rule_severity_check
        CHECK (severity IN ('info', 'warning', 'error'))
);

CREATE TABLE quality_flag (
    id              text PRIMARY KEY,
    submission_id   text NOT NULL REFERENCES submission (id) ON DELETE CASCADE,
    rule_id         text REFERENCES quality_rule (id) ON DELETE SET NULL,
    path            text,
    severity        text NOT NULL,
    detail          jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),
    resolved_at     timestamptz,
    resolved_by     text
);

CREATE INDEX quality_flag_open_idx
    ON quality_flag (submission_id) WHERE resolved_at IS NULL;

CREATE TABLE review (
    id              text PRIMARY KEY,
    submission_id   text NOT NULL REFERENCES submission (id) ON DELETE CASCADE,
    reviewer_id     text NOT NULL,
    decision        text NOT NULL,
    comment         text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT review_decision_check
        CHECK (decision IN ('approved', 'rejected', 'correction_required', 'comment'))
);

-- ===========================================================================
-- WORKFLOW
-- ===========================================================================

CREATE TABLE workflow_definition (
    id              text PRIMARY KEY,
    project_id      text NOT NULL REFERENCES project (id) ON DELETE CASCADE,
    name            text NOT NULL,
    version         integer NOT NULL DEFAULT 1,
    definition      jsonb NOT NULL,
    enabled         boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, name, version)
);

CREATE TABLE workflow_instance (
    id              text PRIMARY KEY,
    definition_id   text NOT NULL REFERENCES workflow_definition (id) ON DELETE RESTRICT,
    subject_type    text NOT NULL,
    subject_id      text NOT NULL,
    state           text NOT NULL,
    sla_due_at      timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    closed_at       timestamptz,
    CONSTRAINT workflow_instance_subject_check
        CHECK (subject_type IN ('submission', 'case', 'visit'))
);

CREATE INDEX workflow_instance_sla_idx
    ON workflow_instance (sla_due_at) WHERE closed_at IS NULL;

CREATE TABLE workflow_transition (
    id              text PRIMARY KEY,
    instance_id     text NOT NULL REFERENCES workflow_instance (id) ON DELETE CASCADE,
    from_state      text,
    to_state        text NOT NULL,
    actor_id        text,
    reason          text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- ===========================================================================
-- INFRASTRUCTURE
-- ===========================================================================

CREATE TABLE audit_event (
    id              text PRIMARY KEY,
    actor_id        text,
    action          text NOT NULL,
    subject_type    text NOT NULL,
    subject_id      text,
    detail          jsonb NOT NULL DEFAULT '{}'::jsonb,
    ip_address      inet,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_event_subject_idx ON audit_event (subject_type, subject_id, created_at);

-- Transactional outbox: events are written in the same transaction as the
-- state change, then published by a worker. No message broker required.
CREATE TABLE outbox_event (
    id              text PRIMARY KEY,
    topic           text NOT NULL,
    payload         jsonb NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    published_at    timestamptz,
    attempts        integer NOT NULL DEFAULT 0,
    last_error      text
);

CREATE INDEX outbox_event_unpublished_idx
    ON outbox_event (created_at) WHERE published_at IS NULL;

CREATE TABLE sync_cursor (
    device_id       text NOT NULL REFERENCES device (id) ON DELETE CASCADE,
    scope           text NOT NULL,
    cursor_value    bigint NOT NULL DEFAULT 0,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (device_id, scope)
);
