"""The OpenAPI contract: the app generates it, the repository commits it, and
these tests are what stop the two parting company.

`specs/openapi.json` and `web/src/api/types.ts` are both generated by
`scripts/generate_api_contract.py`. Committing generated files only buys
anything if something notices when they go stale, so:

* `test_committed_contract_matches_the_app` and
  `test_committed_console_types_match_the_contract` are the byte comparison.
  They catch every change, including ones nobody thought to write a rule for.
* the rest are rules about the *shape* of the document, and they exist because
  the byte comparison alone gives a bad diagnosis. A route added without a
  `response_model` produces a hundred-line diff in a JSON file and no
  explanation; `test_every_success_response_names_a_schema` names the route.

The document is generated, never edited. There is no test for that because
there cannot be one — an edit to `specs/openapi.json` fails the byte comparison
whether it was deliberate or not, which is the point.
"""

import importlib.util
import json
import pathlib
import sys

import pytest

REPO = pathlib.Path(__file__).resolve().parents[2]
GENERATOR = REPO / "scripts" / "generate_api_contract.py"
OPENAPI = REPO / "specs" / "openapi.json"
CONSOLE_TYPES = REPO / "web" / "src" / "api" / "types.ts"

# Statuses whose body FastAPI writes, not us: 422 is request validation. Ours
# are the 2xx, and the 4xx a route raises deliberately.
FRAMEWORK_STATUSES = {"422"}


@pytest.fixture(scope="module")
def generator():
    """The generator script, imported as a module.

    It lives in `scripts/` rather than in the `app` package because it is a
    tool, not part of the server. Importing it by path is the price of that,
    and it is worth paying: the test then exercises the same code CI runs
    rather than a second implementation of it that could agree with the
    committed file while the real generator disagrees.
    """
    spec = importlib.util.spec_from_file_location("generate_api_contract", GENERATOR)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def schema(generator):
    return generator.build_openapi()


def test_committed_contract_matches_the_app(generator, schema):
    """`specs/openapi.json` is what the app generates, byte for byte.

    An API change without a contract change is the failure this exists to
    prevent: the console, the Kotlin clients and anyone integrating read the
    committed file, and a committed file that has fallen behind the server is
    worse than no file at all — it is wrong with an air of authority.
    """
    assert OPENAPI.exists(), f"no committed contract at {OPENAPI}"
    assert OPENAPI.read_text(encoding="utf-8") == generator.render_openapi(schema), (
        "specs/openapi.json is not what the app generates. Run "
        f"`{generator.REGENERATE}` and commit the result, in the same commit as "
        "the API change that caused it."
    )


def test_committed_console_types_match_the_contract(generator, schema):
    """`web/src/api/types.ts` is generated from the same document.

    The console used to hand-mirror `SUBMISSION_STATUSES` from a database CHECK
    constraint and needed a test of its own to notice the copy drifting. This
    is that test's replacement, and it covers every type rather than the four
    somebody remembered to write a rule for.
    """
    assert CONSOLE_TYPES.exists(), f"no generated console types at {CONSOLE_TYPES}"
    assert CONSOLE_TYPES.read_text(encoding="utf-8") == generator.render_types(schema), (
        "web/src/api/types.ts is not what the contract generates. Run "
        f"`{generator.REGENERATE}` and commit the result. Do not edit that file."
    )


def operations(schema):
    """(method, path, operation) for every route in the document."""
    for path, methods in schema["paths"].items():
        for method, operation in methods.items():
            yield method.upper(), path, operation


def test_the_document_covers_every_route(schema):
    """A sanity floor, so a document that silently lost its paths still fails."""
    assert len(list(operations(schema))) >= 16


def test_every_success_response_names_a_schema(schema):
    """Every 2xx body is a `$ref`, never an inline shape.

    This is what `response_model` buys, and the failure it catches is a route
    written without one: FastAPI then infers the body from the return
    annotation, and `dict[str, Any]` infers to `additionalProperties: true` —
    an object with no fields. That generates as `Record<string, unknown>`,
    which type-checks everywhere and describes nothing. The route looks
    documented and is not.
    """
    for method, path, operation in operations(schema):
        for status, response in operation["responses"].items():
            if not status.startswith("2"):
                continue
            content = response.get("content")
            assert content, f"{method} {path} → {status} has no body schema"
            body = content["application/json"]["schema"]
            assert "$ref" in body, (
                f"{method} {path} → {status} returns an inline schema "
                f"({json.dumps(body)[:120]}). Give the route a `response_model` "
                "pointing at a Pydantic model, so the contract names the type "
                "and a generated client can too."
            )


def test_every_request_body_names_a_schema(schema):
    """Same rule for what goes in. A `dict[str, Any]` body documents nothing.

    One media type is exempt, and only one: `application/octet-stream`, which
    is a stream of bytes and has no fields to name. `PUT .../chunks/{n}` takes
    4 MiB of ciphertext that way rather than base64 inside a JSON envelope,
    which would cost a third more on every chunk — on exactly the connections
    resumable upload exists for. The exemption is narrow on purpose: a binary
    body must SAY it is binary, so a route that quietly stopped declaring a
    model still fails here.
    """
    for method, path, operation in operations(schema):
        request = operation.get("requestBody")
        if request is None:
            continue
        content = request["content"]
        binary = content.get("application/octet-stream")
        if binary is not None:
            assert set(content) == {"application/octet-stream"}, (
                f"{method} {path} offers both a binary and a JSON body "
                f"({sorted(content)}). One request, one shape."
            )
            assert binary["schema"].get("type") == "string", (
                f"{method} {path} declares a binary body that is not a byte "
                f"stream ({json.dumps(binary['schema'])[:120]})."
            )
            continue
        body = content["application/json"]["schema"]
        assert "$ref" in body, (
            f"{method} {path} takes an inline request schema "
            f"({json.dumps(body)[:120]}). Declare a Pydantic model for it."
        )


def test_every_declared_error_body_names_a_schema(schema):
    """The error bodies we declare are typed too — and are the real body.

    FastAPI wraps an `HTTPException`'s `detail` in `{"detail": ...}` before it
    reaches the wire, so an error model has to be that envelope. Declaring the
    payload inside it — which this API did for `POST /devices` — publishes a
    contract for a body the server has never returned.
    """
    for method, path, operation in operations(schema):
        for status, response in operation["responses"].items():
            if status.startswith("2") or status in FRAMEWORK_STATUSES:
                continue
            content = response.get("content")
            assert content, f"{method} {path} → {status} has no body schema"
            body = content["application/json"]["schema"]
            assert "$ref" in body, f"{method} {path} → {status} is an inline schema"
            name = body["$ref"].rsplit("/", 1)[-1]
            properties = schema["components"]["schemas"][name]["properties"]
            assert set(properties) == {"detail"}, (
                f"{method} {path} → {status} declares `{name}`, whose fields are "
                f"{sorted(properties)}. FastAPI sends `{{\"detail\": ...}}`; the "
                "declared model must be that envelope, not the payload inside it."
            )


def test_every_closed_value_set_is_a_named_schema(schema):
    """No anonymous enums in the document.

    A `Literal` assigned plainly inlines its members at every use site, so one
    closed set becomes six unrelated unions and a generated client has no name
    to give any of them — nor an array to render a dropdown from. A PEP 695
    `type` alias gets its own entry instead. This test is what keeps the next
    one from being written the old way.

    Query parameters are exempt in one direction only: `anyOf: [$ref, null]` is
    still a ref.
    """
    def walk(node, where):
        if isinstance(node, dict):
            if "enum" in node and where != "components.schemas":
                pytest.fail(
                    f"{where} has an inline enum {node['enum']}. Declare it as "
                    "`type Name = Literal[...]` so the document names it once."
                )
            for key, value in node.items():
                walk(value, f"{where}.{key}")
        elif isinstance(node, list):
            for index, value in enumerate(node):
                walk(value, f"{where}[{index}]")

    for name, component in schema["components"]["schemas"].items():
        # The component itself is allowed to BE an enum; its properties are not.
        walk(component.get("properties", {}), f"components.schemas.{name}.properties")
    walk(schema["paths"], "paths")
