#!/usr/bin/env python3
"""Every §4.3 function and operator, against every shape of value.

    python conformance/generate_function_matrix.py

## Why this set exists

The other vector sets are chosen cases: somebody thought of a construct and
wrote it down. That is exactly the limitation the coverage ledger was built
around one layer up — such a test can only fail on an input somebody thought
of — and the function library had the same hole for its whole existence.

Nothing in the corpus had ever put **text where a number belongs**, because
until dataset columns existed nothing could: every value in a form came from a
typed question. A CSV holds nothing but text, so `int($row.population)` made it
an everyday case overnight, and the first two dataset vectors that used it
failed on Kotlin. The sweep that followed ran every function and operator
against every value shape on both engines and found **762 of 1,395 probes
disagreeing**, none of them covered by a vector (break 46).

So this set is not chosen at all. It is the cross product, and its value is
exactly that nobody picked the cases.

## What the expectations are, and where they come from

Form IR §4.7 is the rule:

  - an argument that is not of the type §4.3 declares is null, and a function
    with such an argument yields null
  - evaluation raises for exactly one reason: integer overflow (§4.5)
  - `eq` / `ne` are total across types — different types are simply not equal
  - `concat` renders rather than refuses

The expectations in `fn.spec.json` are **typed by hand from §4.7's own table**
and are the anchor. The rest are generated by evaluating the Python reference,
which docs/project-conventions.md makes the definition when behaviour is ambiguous — and were
checked class by class against the rule rather than row by row, because 1,395
rows reviewed individually is a review nobody does properly.

Regenerating after a deliberate semantic change is legitimate and is a spec
change; regenerating to make a failure go away is the thing rule 3 forbids.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "backend"))

from datetime import date, datetime  # noqa: E402

from app.modules.form_engine.expression import (  # noqa: E402
    EvalContext,
    evaluate,
)

OUT = pathlib.Path(__file__).parent / "functions"

TODAY = "2026-08-28"

#: One of each shape a value can have, including the three that used to be
#: impossible in a form and are now ordinary: text that looks like a number,
#: text that does not, and text that is a date.
SHAPES: dict[str, object] = {
    "null": None,
    "text_num": "800",
    "text_pad": " 800 ",
    "text_bad": "8a",
    "text_empty": "",
    "text_date": "2026-01-15",
    "int": 800,
    "dec": 800.5,
    "bool": True,
    "seq": ["a", "b"],
}

#: A smaller pool for the binary cross-product, so the set stays readable.
#: Every kind is represented; only the near-duplicates are dropped.
BINARY_SHAPES = ["null", "text_num", "text_bad", "text_date", "int", "dec", "bool"]

UNARY_FNS = [
    "int", "dec", "str", "len", "upper", "lower", "trim", "count", "sum",
    "min", "max", "count_selected", "is_null", "is_not_null", "round",
]
BINARY_FNS = [
    "contains", "starts_with", "ends_with", "regex", "substr", "round",
    "date_diff_days", "date_add_days", "age_years", "concat",
]
UNARY_OPS = ["not", "neg"]
BINARY_OPS = [
    "eq", "ne", "lt", "lte", "gt", "gte", "add", "sub", "mul", "div",
    "idiv", "mod", "and", "or", "selected",
]


def lit(value: object) -> dict:
    return {"op": "lit", "value": value}


def _context() -> EvalContext:
    today = date.fromisoformat(TODAY)
    return EvalContext(
        values={}, today=today, now=datetime.combine(today, datetime.min.time())
    )


def _evaluate(expr: dict) -> tuple[object, str | None]:
    """The reference's answer, and the name of what it raised if it did."""
    try:
        return evaluate(expr, _context()), None
    except Exception as failure:  # noqa: BLE001 - the point is to record it
        return None, type(failure).__name__


def _probe(probe_id: str, expr: dict) -> dict:
    value, raised = _evaluate(expr)
    entry: dict = {"id": probe_id, "expr": expr}
    if raised is not None:
        # §4.7 permits exactly one: integer overflow. Anything else appearing
        # here is a bug being frozen into the set, so it is refused outright.
        if raised != "EvaluationError":
            raise SystemExit(
                f"{probe_id}: the reference raised {raised}. §4.7 makes "
                "evaluation total apart from integer overflow — fix the engine "
                "rather than recording the exception as an expectation."
            )
        entry["raises"] = "integer overflow"
    else:
        entry["expect"] = value
    return entry


def build() -> dict[str, dict]:
    files: dict[str, list[dict]] = {}

    def add(group: str, probe_id: str, expr: dict) -> None:
        files.setdefault(group, []).append(_probe(probe_id, expr))

    for fn in UNARY_FNS:
        for name, value in SHAPES.items():
            add(f"fn.{fn}", f"fn.{fn}.{name}", {"op": "call", "fn": fn, "args": [lit(value)]})

    for op in UNARY_OPS:
        for name, value in SHAPES.items():
            add(f"op.{op}", f"op.{op}.{name}", {"op": op, "args": [lit(value)]})

    for fn in BINARY_FNS:
        for a in BINARY_SHAPES:
            for b in BINARY_SHAPES:
                add(
                    f"fn.{fn}",
                    f"fn.{fn}.{a}.{b}",
                    {"op": "call", "fn": fn, "args": [lit(SHAPES[a]), lit(SHAPES[b])]},
                )

    for op in BINARY_OPS:
        for a in BINARY_SHAPES:
            for b in BINARY_SHAPES:
                add(
                    f"op.{op}",
                    f"op.{op}.{a}.{b}",
                    {"op": op, "args": [lit(SHAPES[a]), lit(SHAPES[b])]},
                )

    # The one thing §4.7 leaves as an error, so that "evaluation is total apart
    # from integer overflow" is asserted rather than asserted-about.
    add(
        "op.overflow",
        "op.overflow.mul",
        {"op": "mul", "args": [lit(4_000_000_000), lit(4_000_000_000)]},
    )
    add(
        "op.overflow.add",
        "op.overflow.add",
        {"op": "add", "args": [lit(9_223_372_036_854_775_807), lit(1)]},
    )

    return {
        group: {
            "id": group,
            "description": f"Every value shape through `{group.split('.', 1)[1]}`",
            "spec": "4.3, 4.7",
            "context": {"today": TODAY},
            "probes": probes,
        }
        for group, probes in files.items()
    }


#: §4.7's own worked examples, typed from the specification rather than
#: generated. The anchor: if the generated bulk ever drifts from the rule, the
#: rule is still written down here in a form both engines execute.
SPEC_EXAMPLES = [
    ("len_of_sequence", {"op": "call", "fn": "len", "args": [lit(["a", "b"])]}, None),
    ("upper_of_number", {"op": "call", "fn": "upper", "args": [lit(800)]}, None),
    ("substr_of_number", {"op": "call", "fn": "substr", "args": [lit(800), lit(0)]}, None),
    (
        "contains_of_boolean",
        {"op": "call", "fn": "contains", "args": [lit(True), lit("a")]},
        None,
    ),
    ("round_of_text", {"op": "call", "fn": "round", "args": [lit("800.7")]}, None),
    (
        "round_digits_text",
        {"op": "call", "fn": "round", "args": [lit(1.5), lit("2")]},
        None,
    ),
    ("sum_ignores_text", {"op": "call", "fn": "sum", "args": [lit(["a", 3])]}, 3),
    ("min_of_text_only", {"op": "call", "fn": "min", "args": [lit(["a", "b"])]}, None),
    (
        "date_diff_of_bad_text",
        {"op": "call", "fn": "date_diff_days", "args": [lit("8a"), lit("2026-01-01")]},
        None,
    ),
    (
        "date_add_text_days",
        {"op": "call", "fn": "date_add_days", "args": [lit("2026-01-01"), lit("3")]},
        None,
    ),
    ("add_text_to_number", {"op": "add", "args": [lit("800"), lit(1)]}, None),
    ("add_two_booleans", {"op": "add", "args": [lit(True), lit(True)]}, None),
    ("neg_of_text", {"op": "neg", "args": [lit("800")]}, None),
    ("not_of_text", {"op": "not", "args": [lit("yes")]}, None),
    ("order_across_types", {"op": "lt", "args": [lit("800"), lit(100)]}, None),
    # The exception, and the reason §4.7 spells it out: this is `false`, not null.
    ("equality_across_types", {"op": "eq", "args": [lit("800"), lit(800)]}, False),
    (
        "inequality_across_types",
        {"op": "ne", "args": [lit("800"), lit(800)]},
        True,
    ),
    (
        "if_with_text_condition",
        {"op": "if", "args": [lit("yes"), lit("a"), lit("b")]},
        None,
    ),
    (
        "distance_of_text",
        {"op": "call", "fn": "distance", "args": [lit("a"), lit("b")]},
        None,
    ),
    # concat renders rather than refuses.
    (
        "concat_renders_a_number",
        {"op": "call", "fn": "concat", "args": [lit("n="), lit(3)]},
        "n=3",
    ),
    (
        "concat_treats_null_as_empty",
        {"op": "call", "fn": "concat", "args": [lit("a"), lit(None), lit("b")]},
        "ab",
    ),
    # The cast that makes a text column comparable at all (§4.3.1, §3.2).
    (
        "str_of_whole_decimal_matches_a_text_cell",
        {"op": "eq", "args": [{"op": "call", "fn": "str", "args": [lit(800.0)]}, lit("800")]},
        True,
    ),
]


def spec_file() -> dict:
    probes = []
    for name, expr, expected in SPEC_EXAMPLES:
        value, raised = _evaluate(expr)
        if raised is not None:
            raise SystemExit(f"spec example {name} raised {raised}")
        if value != expected or type(value) is not type(expected):
            raise SystemExit(
                f"spec example {name}: §4.7 says {expected!r}, the reference "
                f"says {value!r}. One of the two is wrong and it is not this file's "
                "job to decide which — fix the engine, or change the spec "
                "deliberately and in its own commit."
            )
        probes.append({"id": f"spec.{name}", "expr": expr, "expect": expected})
    return {
        "id": "fn.spec",
        "description": "§4.7's own worked examples, typed from the specification",
        "spec": "4.7",
        "context": {"today": TODAY},
        "probes": probes,
    }


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for existing in OUT.glob("*.json"):
        existing.unlink()

    files = build()
    files["fn.spec"] = spec_file()
    total = 0
    for name, document in sorted(files.items()):
        (OUT / f"{name}.json").write_text(
            json.dumps(document, indent=1, ensure_ascii=False) + "\n"
        )
        total += len(document["probes"])
    print(f"wrote {len(files)} files, {total} probes to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
